# backend/docker-compose.yml

services:
  db:
    image: postgres
    container_name: eweave-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:  # New: Backend app service
    build: .  # Builds from your Dockerfile
    container_name: eweave-backend
    restart: unless-stopped
    ports:
      - "3000:3000"  # Expose backend port
    env_file: .env  # Loads env vars at runtime (secure)
    depends_on:
      - db  # Waits for DB to start
    volumes:
      - .:/app  # For dev hot-reload (remove in prod)
      - /app/node_modules  # Persist node_modules

volumes:
  postgres_data: